# See https://docs.gitbook.com/integrations/git-sync/content-configuration for documentation
root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  centering/1: 1.md
  centering/2: 2.md
  centering/3: 3.md
